### ISSUE TITLE
Unable to bind an event on a combobox

### ISSUE THREAD

**Issue by rmcgibbo** [alfiopuglisi/guietta#15]
I'm not sure if this is a bug or user error.  This is on the master branch.

```
# example.py
from guietta import Gui, CB

def change(gui, value):
    print(value)

gui = Gui(
    [CB("op", ["a", "b", "c"])]
)

gui.events([change])
gui.run()
```

Errors with
```
Traceback (most recent call last):
  File "/nix/store/qkci2s9sqjdbr3dlzvlnv7xywma2s296-python3-3.7.6-env/lib/python3.7/site-packages/guietta/guietta.py", line 1387, in _connect
    signal = getattr(widget, signal_name)
AttributeError: 'ContextQComboBox' object has no attribute 'textActivated'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "guietta-example.py", line 9, in <module>
    gui.events([change])
  File "/nix/store/qkci2s9sqjdbr3dlzvlnv7xywma2s296-python3-3.7.6-env/lib/python3.7/site-packages/guietta/guietta.py", line 1631, in events
    _connect(self, item, signal_name, slot)
  File "/nix/store/qkci2s9sqjdbr3dlzvlnv7xywma2s296-python3-3.7.6-env/lib/python3.7/site-packages/guietta/guietta.py", line 1390, in _connect
    (signal_name, str(widget.__class__))) from e
ValueError: No signal textActivated found for widget <class 'guietta.guietta.ContextQComboBox'>
```

**Comment by rmcgibbo** [comment]
I think the issue may be that this signal was added in Qt 5.14, whereas I have Qt 5.12.

It appears perfectly fixed to my eye by mucking with the default signals to use `currentTextChanged`
```
from PySide2.QtWidgets import QComboBox
guietta._default_signals[QComboBox] = 'currentTextChanged'
```

**Comment by alfiopuglisi** [comment]
You are right, I changed the default signal. I didn't notice that this signal was so new.
