### ISSUE TITLE
with statement error in python 3.11

### ISSUE THREAD

**Issue by chenbotao828** [alfiopuglisi/guietta#48]
Hi.

I was learning with python 3.11, code :

````
  from guietta import _, Gui, Quit
  
  gui = Gui(
  
      ['Enter numbers:', '__a__', '+', '__b__', ['Calculate']],
      ['Result:  -->', 'result', _, _, _],
      [_, _, _, _, Quit])
  with gui.Calculate:
      gui.result = float(gui.a) + float(gui.b)
  
  gui.run()
````

the result:

````
Traceback (most recent call last):
  File "C:\Users\app.py", line 9, in <module>
    gui.result = float(gui.a) + float(gui.b)
                 ^^^^^^^^^^^^
ValueError: could not convert string to float: ''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\app.py", line 8, in <module>
    with gui.Calculate:
  File "D:\Anaconda3\envs\app\Lib\site-packages\guietta\guietta.py", line 164, in __exit__
    tree = ast.parse(withsource)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda3\envs\app\Lib\ast.py", line 50, in parse
    return compile(source, filename, mode, flags,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<unknown>", line 1
    with gui.Calculate:
                       ^
IndentationError: expected an indented block after 'with' statement on line 1
````

Is with statement not working in python 3.11 ? Or is there an alternative way of doing that? Thanks

**Comment by alfiopuglisi** [comment]
Thanks for the bug report, it was indeed a bug on python 3.11 and later versions.

It should be fixed in version 1.6.1, which is now available on pip.
