### ISSUE TITLE
get() does not work correctly with non-default arguments.

### ISSUE THREAD

**Issue by masasin** [alfiopuglisi/guietta#5]
Examples:

* `block = False`, regardless of timeout:

    ```
    Traceback (most recent call last):
      File "gui.py", line 36, in <module>
        name, event = gui.get(block=False)
      File "/tmp/gui/.pyenv/lib/python3.8/site-packages/guietta/guietta.py", line 1652, in get
        QTimer.singleShot(timeout * 1000,
    TypeError: 'PySide2.QtCore.QTimer.singleShot' called with wrong argument types:
      PySide2.QtCore.QTimer.singleShot(int, TimerType, method)
    Supported signatures:
      PySide2.QtCore.QTimer.singleShot(int, typing.Callable)
      PySide2.QtCore.QTimer.singleShot(int, PySide2.QtCore.QObject, bytes)
      PySide2.QtCore.QTimer.singleShot(int, PySide2.QtCore.Qt.TimerType, PySide2.QtCore.QObject, bytes)

    shell returned 1
    ```

* `timeout = anything` (even an int):

    ```
    Traceback (most recent call last):
      File "gui.py", line 36, in <module>
        name, event = gui.get(timeout=0.1)
      File "/tmp/gui/.pyenv/lib/python3.8/site-packages/guietta/guietta.py", line 1652, in get
        QTimer.singleShot(timeout * 1000,
    TypeError: 'PySide2.QtCore.QTimer.singleShot' called with wrong argument types:
      PySide2.QtCore.QTimer.singleShot(float, TimerType, method)
    Supported signatures:
      PySide2.QtCore.QTimer.singleShot(int, typing.Callable)
      PySide2.QtCore.QTimer.singleShot(int, PySide2.QtCore.QObject, bytes)
      PySide2.QtCore.QTimer.singleShot(int, PySide2.QtCore.Qt.TimerType, PySide2.QtCore.QObject, bytes)

    shell returned 1
    ```

**Comment by alfiopuglisi** [comment]
I am not sure what happened (it has been a while since I have used the queue mode), but it appears that I was calling QTimer.singleShot() wrong. I have removed the PreciseTimer specification and now it works for me. Commited as 93ce1a26. Can you give it a try too?

**Comment by masasin** [comment]
@alfiopuglisi It worked. Thanks!
